name: Publish to Comfy registry
on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - "pyproject.toml"

jobs:
  publish-node:
    name: Publish Custom Node to registry
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v4
      
      - name: Debug - Check pyproject.toml
        run: |
          echo "=== pyproject.toml content ==="
          cat pyproject.toml
          echo "=== End pyproject.toml ==="
      
      - name: Debug - Check secrets
        run: |
          if [ -n "${{ secrets.REGISTRY_ACCESS_TOKEN }}" ]; then
            echo "REGISTRY_ACCESS_TOKEN is set"
          else
            echo "REGISTRY_ACCESS_TOKEN is NOT set"
          fi
      
      - name: Publish Custom Node
        uses: Comfy-Org/publish-node-action@main
        with:
          personal_access_token: ${{ secrets.REGISTRY_ACCESS_TOKEN }}
        continue-on-error: true
      
      - name: Debug - Check publish result
        run: |
          echo "Publish step completed"
          echo "Check the previous step for detailed error information"
